title: Stochastic Code Monkeys
description: Thoughts, stories and ideas.
url: https://www.stochasticcodemonkeys.com
lang: en
source_url: https://github.com/gravitymonkey/scm-site
author_url: https://github.com/gravitymonkey
author_name: gravitymonkey
